### ISSUE TITLE
Proile migrations from custom files result in error "ProcessModule: ___include: File is not in an allowed path"

### ISSUE THREAD

**Issue by ivangretsky** [baumrock/RockMigrations#28]
Hi @BernhardBaumrock !

I am testing running profile migrations from `site/assets/RockMigrations/profiles`. The profile is shown in the dropdown and can be selected. But running it results in this error:

```
ProcessWire: ProcessModule: ___include: File is not in an allowed path: /XYZ/site/assets/RockMigrations/profiles/PROFILE.php
```

Maybe it would be better to place the profile folder somewhere under `templates`?

**Comment by BernhardBaumrock** [comment]
@ivangretsky  is this still an issue?

**Comment by tiberium-v** [comment]
Sry to re-open this, but i tried this function today for the first time, with a fresh pw installation and have the issue as describe above. 


```
ProcessWire: ProcessModule: ___include: File is not in an allowed path: /var/www/html/site/assets/RockMigrations/profiles/awb_modules.php

DEBUG MODUS ABLAUFVERFOLGUNG ($config->debug == true):
#0 /var/www/html/wire/core/WireFileTools.php(2003): ProcessWire\WireFileTools->filesError('___include', '___include: Fil...', true, NULL)
#1 /var/www/html/wire/core/WireFileTools.php(1591): ProcessWire\WireFileTools->filesException('___include', 'File is not in ...')
#2 /var/www/html/wire/core/Wire.php(416): ProcessWire\WireFileTools->___include('/var/www/html/s...')
#3 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___include', Array)
#4 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\WireFileTools), 'include', Array)
#5 /var/www/html/site/modules/RockMigrations/RockMigrations.module.php(3318): ProcessWire\Wire->__call('include', Array)
#6 /var/www/html/site/modules/RockMigrations/RockMigrations.module.php(5788): ProcessWire\RockMigrations->profileExecute()
#7 /var/www/html/wire/core/ModulesConfigs.php(595): ProcessWire\RockMigrations->getModuleConfigInputfields(Object(ProcessWire\InputfieldWrapper))
#8 /var/www/html/wire/core/Modules.php(1744): ProcessWire\ModulesConfigs->getModuleConfigInputfields('RockMigrations', Object(ProcessWire\InputfieldForm))
#9 /var/www/html/wire/core/Wire.php(419): ProcessWire\Modules->___getModuleConfigInputfields('RockMigrations', Object(ProcessWire\InputfieldForm))
#10 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___getModuleCon...', Array)
#11 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Modules), 'getModuleConfig...', Array)
#12 /var/www/html/wire/modules/Process/ProcessModule/ProcessModule.module(1705): ProcessWire\Wire->__call('getModuleConfig...', Array)
#13 /var/www/html/wire/modules/Process/ProcessModule/ProcessModule.module(1435): ProcessWire\ProcessModule->renderEdit('RockMigrations', Array)
#14 /var/www/html/wire/core/Wire.php(413): ProcessWire\ProcessModule->___executeEdit()
#15 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___executeEdit', Array)
#16 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessModule), 'executeEdit', Array)
#17 /var/www/html/wire/core/ProcessController.php(361): ProcessWire\Wire->__call('executeEdit', Array)
#18 /var/www/html/wire/core/Wire.php(413): ProcessWire\ProcessController->___execute()
#19 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___execute', Array)
#20 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessController), 'execute', Array)
#21 /var/www/html/wire/core/admin.php(174): ProcessWire\Wire->__call('execute', Array)
#22 /var/www/html/site/templates/admin.php(18): require('/var/www/html/w...')
#23 /var/www/html/wire/core/TemplateFile.php(328): require('/var/www/html/s...')
#24 /var/www/html/wire/core/Wire.php(413): ProcessWire\TemplateFile->___render()
#25 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___render', Array)
#26 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array)
#27 /var/www/html/wire/modules/PageRender.module(581): ProcessWire\Wire->__call('render', Array)
#28 /var/www/html/wire/core/Wire.php(416): ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent))
#29 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___renderPage', Array)
#30 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\PageRender), 'renderPage', Array)
#31 /var/www/html/wire/core/WireHooks.php(1094): ProcessWire\Wire->__call('renderPage', Array)
#32 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\Page), 'render', Array)
#33 /var/www/html/wire/modules/Process/ProcessPageView.module(184): ProcessWire\Wire->__call('render', Array)
#34 /var/www/html/wire/modules/Process/ProcessPageView.module(114): ProcessWire\ProcessPageView->renderPage(Object(ProcessWire\Page), Object(ProcessWire\PagesRequest))
#35 /var/www/html/wire/core/Wire.php(416): ProcessWire\ProcessPageView->___execute(true)
#36 /var/www/html/wire/core/WireHooks.php(968): ProcessWire\Wire->_callMethod('___execute', Array)
#37 /var/www/html/wire/core/Wire.php(484): ProcessWire\WireHooks->runHooks(Object(ProcessWire\ProcessPageView), 'execute', Array)
#38 /var/www/html/index.php(55): ProcessWire\Wire->__call('execute', Array)
#39 {main}
```

The file i created are a copy of the example in the migration module config page. I only comment two modules out.

**Comment by ivangretsky** [comment]
Seems like it is. I have not tried it since then.

**Comment by ivangretsky** [comment]
> @ivangretsky is this still an issue?

Seems like it is. I have not tried it since then.
