### ISSUE TITLE
Adding a Repeater Matrix

### ISSUE THREAD

**Issue by nloyola** [baumrock/RockMigrations#5]
I'm getting the following error when trying to add a Repeater Matrix via Rock Migrations:

```
ProcessWire: ProcessModule: Method RockMigrations::getRepeaterTemplate does not exist or is not callable in this context

DEBUG MODE BACKTRACE ($config->debug == true):
#0 /opt/norweb/norweb-2021/public/wire/core/Wire.php(420): ProcessWire\Wire->___callUnknown('getRepeaterTemp...', Array)
#1 /opt/norweb/norweb-2021/public/wire/core/WireHooks.php(951): ProcessWire\Wire->_callMethod('___callUnknown', Array)
#2 /opt/norweb/norweb-2021/public/wire/core/Wire.php(485): ProcessWire\WireHooks->runHooks(Object(ProcessWire\RockMigrations), 'callUnknown', Array)
#3 /opt/norweb/norweb-2021/public/wire/core/Wire.php(488): ProcessWire\Wire->__call('callUnknown', Array)
#4 /opt/norweb/norweb-2021/public/site/modules/RockMigrations/RockMigrations.module.php(2539): ProcessWire\Wire->__call('getRepeaterTemp...', Array)
#5 /opt/norweb/norweb-2021/public/site/modules/RockMigrations/RockMigrations.module.php(824): ProcessWire\RockMigrations->setFieldData(Object(ProcessWire\RepeaterMatrixField), Array)
#6 /opt/norweb/norweb-2021/src/PwMigration/NorwebMigration.php(112): ProcessWire\RockMigrations->createField('components', 'FieldtypeRepeat...', Array)
#7 /opt/norweb/norweb-2021/src/PwMigration/NorwebMigration.php(103): Nordita\Norweb\PwMigration\NorwebMigration->addFields(Array)
#8 /opt/norweb/norweb-2021/public/site/migrate.php(14): Nordita\Norweb\PwMigration\NorwebMigration->migrate(Object(ProcessWire\RockMigrations))
#9 /opt/norweb/norweb-2021/public/wire/core/TemplateFile.php(327): require('/opt/norweb/nor...')
#10 /opt/norweb/norweb-2021/public/wire/core/Wire.php(414): ProcessWire\TemplateFile->___render()
```

I'm using the same code that worked before with the previous version of the RockMigrations module.

How can I fix this?

Thank you

**Comment by BernhardBaumrock** [comment]
I've not added support for RepeaterMatrix yet. You can go to the latest version of the old module and copy the necessary methods into the new module. That's what I'm doing if I find something that does not work on the new version but has worked on the old one.

I don't have any projects using RepeaterMatrix so support for it does not have priority unless someone sponsors it.

But if you are in need of something like a pagebuilder you can write me a PM in the forum and maybe use RockMatrix instead which is a  much better page builder than RepeaterMatrix imho :)

**Comment by nloyola** [comment]
I forgot to mention that I'm using RockMigrations 0.15.0.

**Comment by BernhardBaumrock** [comment]
@nloyola thx for the report, I've added a note about that in the readme
